language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories: "— node_modules"
branches:
  only:
  - master
install:
- yarn
script:
- gulp default --prod
deploy:
  provider: heroku
  api_key:
    secure: F9xl23dyGenOvSTkMFtFs6yGnVrNnu51cIJB5U+o457TrTpEb0i0XNbNjcj+E++TDad8VT6NZ6mYc1kJYSvy3mRtOeBcDp7KBnT58DWX6G21VQqhMyWDdqB+Je6BShtL4G9kb6GHnzEW8+zqlm1t2u5gWzqrBvDxgjQh8hSJO2KIqH9KtJ7qDkzsG33qsh+tV1Wh2wJpIdUpK+tEpR3KQtfq0B/NTcIUOdEOPtHEQ/X/pGd6g1fRZTwAbvwZv+zWGWzaYqxVMdVkMzbQGp2hk6puipVHJfdumSCG1zU1HMKLXrcfDIrwbKaL0A6B1vWZpge2jYTjx/VfXBm65/o3743VBnTnBCuQMRMVxOkeMQ6jUz5Y5s+oG7Vz1XCaGWncxz7uQddmFcrwf/nYRFMy4kxnpNSC6e0C7rJ4eD+sTli/TxZ7+2cUU839FYzASna0A8dZsV7e2r+LVKq/59FAdqY2zSzJI0aQLIVmoMq5bVdIvmSNoXW56Yvtw2FmVXYGf4PqtaJQVzHUFnWLXDk3TtDIIzLYxX8nRk5N52ycGXPyaSMNYUDIW2IHSRAS0g9RdOOY5qFwwSeBgmaSrdc6i7n84+hQjBmKyCabNKsWnpIz+cxKqccM/8Jollag9QRELPdgGy3MwKyLFUWZdQ7PNSwlZDzwOWVuNlCdREwDTDE=
